/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AssetExitFormForVendor } from "./AssetExitFormForVendor";
import { AssetExitFormForVendorCountArgs } from "./AssetExitFormForVendorCountArgs";
import { AssetExitFormForVendorFindManyArgs } from "./AssetExitFormForVendorFindManyArgs";
import { AssetExitFormForVendorFindUniqueArgs } from "./AssetExitFormForVendorFindUniqueArgs";
import { DeleteAssetExitFormForVendorArgs } from "./DeleteAssetExitFormForVendorArgs";
import { AssetExitFormForVendorService } from "../assetExitFormForVendor.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AssetExitFormForVendor)
export class AssetExitFormForVendorResolverBase {
  constructor(
    protected readonly service: AssetExitFormForVendorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AssetExitFormForVendor",
    action: "read",
    possession: "any",
  })
  async _assetExitFormForVendorsMeta(
    @graphql.Args() args: AssetExitFormForVendorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AssetExitFormForVendor])
  @nestAccessControl.UseRoles({
    resource: "AssetExitFormForVendor",
    action: "read",
    possession: "any",
  })
  async assetExitFormForVendors(
    @graphql.Args() args: AssetExitFormForVendorFindManyArgs
  ): Promise<AssetExitFormForVendor[]> {
    return this.service.assetExitFormForVendors(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AssetExitFormForVendor, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AssetExitFormForVendor",
    action: "read",
    possession: "own",
  })
  async assetExitFormForVendor(
    @graphql.Args() args: AssetExitFormForVendorFindUniqueArgs
  ): Promise<AssetExitFormForVendor | null> {
    const result = await this.service.assetExitFormForVendor(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AssetExitFormForVendor)
  @nestAccessControl.UseRoles({
    resource: "AssetExitFormForVendor",
    action: "delete",
    possession: "any",
  })
  async deleteAssetExitFormForVendor(
    @graphql.Args() args: DeleteAssetExitFormForVendorArgs
  ): Promise<AssetExitFormForVendor | null> {
    try {
      return await this.service.deleteAssetExitFormForVendor(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
