/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  AssetExitFormForVendor as PrismaAssetExitFormForVendor,
} from "@prisma/client";

export class AssetExitFormForVendorServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AssetExitFormForVendorCountArgs, "select">
  ): Promise<number> {
    return this.prisma.assetExitFormForVendor.count(args);
  }

  async assetExitFormForVendors(
    args: Prisma.AssetExitFormForVendorFindManyArgs
  ): Promise<PrismaAssetExitFormForVendor[]> {
    return this.prisma.assetExitFormForVendor.findMany(args);
  }
  async assetExitFormForVendor(
    args: Prisma.AssetExitFormForVendorFindUniqueArgs
  ): Promise<PrismaAssetExitFormForVendor | null> {
    return this.prisma.assetExitFormForVendor.findUnique(args);
  }
  async createAssetExitFormForVendor(
    args: Prisma.AssetExitFormForVendorCreateArgs
  ): Promise<PrismaAssetExitFormForVendor> {
    return this.prisma.assetExitFormForVendor.create(args);
  }
  async updateAssetExitFormForVendor(
    args: Prisma.AssetExitFormForVendorUpdateArgs
  ): Promise<PrismaAssetExitFormForVendor> {
    return this.prisma.assetExitFormForVendor.update(args);
  }
  async deleteAssetExitFormForVendor(
    args: Prisma.AssetExitFormForVendorDeleteArgs
  ): Promise<PrismaAssetExitFormForVendor> {
    return this.prisma.assetExitFormForVendor.delete(args);
  }
}
