/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AssetExitFormForVendorService } from "../assetExitFormForVendor.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AssetExitFormForVendorCreateInput } from "./AssetExitFormForVendorCreateInput";
import { AssetExitFormForVendor } from "./AssetExitFormForVendor";
import { AssetExitFormForVendorFindManyArgs } from "./AssetExitFormForVendorFindManyArgs";
import { AssetExitFormForVendorWhereUniqueInput } from "./AssetExitFormForVendorWhereUniqueInput";
import { AssetExitFormForVendorUpdateInput } from "./AssetExitFormForVendorUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AssetExitFormForVendorControllerBase {
  constructor(
    protected readonly service: AssetExitFormForVendorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AssetExitFormForVendor })
  @nestAccessControl.UseRoles({
    resource: "AssetExitFormForVendor",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAssetExitFormForVendor(
    @common.Body() data: AssetExitFormForVendorCreateInput
  ): Promise<AssetExitFormForVendor> {
    return await this.service.createAssetExitFormForVendor({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AssetExitFormForVendor] })
  @ApiNestedQuery(AssetExitFormForVendorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AssetExitFormForVendor",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async assetExitFormForVendors(
    @common.Req() request: Request
  ): Promise<AssetExitFormForVendor[]> {
    const args = plainToClass(
      AssetExitFormForVendorFindManyArgs,
      request.query
    );
    return this.service.assetExitFormForVendors({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AssetExitFormForVendor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssetExitFormForVendor",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async assetExitFormForVendor(
    @common.Param() params: AssetExitFormForVendorWhereUniqueInput
  ): Promise<AssetExitFormForVendor | null> {
    const result = await this.service.assetExitFormForVendor({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AssetExitFormForVendor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssetExitFormForVendor",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAssetExitFormForVendor(
    @common.Param() params: AssetExitFormForVendorWhereUniqueInput,
    @common.Body() data: AssetExitFormForVendorUpdateInput
  ): Promise<AssetExitFormForVendor | null> {
    try {
      return await this.service.updateAssetExitFormForVendor({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AssetExitFormForVendor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssetExitFormForVendor",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAssetExitFormForVendor(
    @common.Param() params: AssetExitFormForVendorWhereUniqueInput
  ): Promise<AssetExitFormForVendor | null> {
    try {
      return await this.service.deleteAssetExitFormForVendor({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
