/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Delivery } from "./Delivery";
import { DeliveryCountArgs } from "./DeliveryCountArgs";
import { DeliveryFindManyArgs } from "./DeliveryFindManyArgs";
import { DeliveryFindUniqueArgs } from "./DeliveryFindUniqueArgs";
import { CreateDeliveryArgs } from "./CreateDeliveryArgs";
import { UpdateDeliveryArgs } from "./UpdateDeliveryArgs";
import { DeleteDeliveryArgs } from "./DeleteDeliveryArgs";
import { Product } from "../../product/base/Product";
import { DeliveryService } from "../delivery.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Delivery)
export class DeliveryResolverBase {
  constructor(
    protected readonly service: DeliveryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Delivery",
    action: "read",
    possession: "any",
  })
  async _deliveriesMeta(
    @graphql.Args() args: DeliveryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Delivery])
  @nestAccessControl.UseRoles({
    resource: "Delivery",
    action: "read",
    possession: "any",
  })
  async deliveries(
    @graphql.Args() args: DeliveryFindManyArgs
  ): Promise<Delivery[]> {
    return this.service.deliveries(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Delivery, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Delivery",
    action: "read",
    possession: "own",
  })
  async delivery(
    @graphql.Args() args: DeliveryFindUniqueArgs
  ): Promise<Delivery | null> {
    const result = await this.service.delivery(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Delivery)
  @nestAccessControl.UseRoles({
    resource: "Delivery",
    action: "create",
    possession: "any",
  })
  async createDelivery(
    @graphql.Args() args: CreateDeliveryArgs
  ): Promise<Delivery> {
    return await this.service.createDelivery({
      ...args,
      data: {
        ...args.data,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Delivery)
  @nestAccessControl.UseRoles({
    resource: "Delivery",
    action: "update",
    possession: "any",
  })
  async updateDelivery(
    @graphql.Args() args: UpdateDeliveryArgs
  ): Promise<Delivery | null> {
    try {
      return await this.service.updateDelivery({
        ...args,
        data: {
          ...args.data,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Delivery)
  @nestAccessControl.UseRoles({
    resource: "Delivery",
    action: "delete",
    possession: "any",
  })
  async deleteDelivery(
    @graphql.Args() args: DeleteDeliveryArgs
  ): Promise<Delivery | null> {
    try {
      return await this.service.deleteDelivery(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "read",
    possession: "any",
  })
  async getProduct(
    @graphql.Parent() parent: Delivery
  ): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
