/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StateStoreService } from "../stateStore.service";
import { StateStoreCreateInput } from "./StateStoreCreateInput";
import { StateStore } from "./StateStore";
import { StateStoreFindManyArgs } from "./StateStoreFindManyArgs";
import { StateStoreWhereUniqueInput } from "./StateStoreWhereUniqueInput";
import { StateStoreUpdateInput } from "./StateStoreUpdateInput";
import { WarehouseFindManyArgs } from "../../warehouse/base/WarehouseFindManyArgs";
import { Warehouse } from "../../warehouse/base/Warehouse";
import { WarehouseWhereUniqueInput } from "../../warehouse/base/WarehouseWhereUniqueInput";

export class StateStoreControllerBase {
  constructor(protected readonly service: StateStoreService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: StateStore })
  async createStateStore(
    @common.Body() data: StateStoreCreateInput
  ): Promise<StateStore> {
    return await this.service.createStateStore({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        location: true,
        stateId: true,
        managerId: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [StateStore] })
  @ApiNestedQuery(StateStoreFindManyArgs)
  async stateStores(@common.Req() request: Request): Promise<StateStore[]> {
    const args = plainToClass(StateStoreFindManyArgs, request.query);
    return this.service.stateStores({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        location: true,
        stateId: true,
        managerId: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: StateStore })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async stateStore(
    @common.Param() params: StateStoreWhereUniqueInput
  ): Promise<StateStore | null> {
    const result = await this.service.stateStore({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        location: true,
        stateId: true,
        managerId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: StateStore })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStateStore(
    @common.Param() params: StateStoreWhereUniqueInput,
    @common.Body() data: StateStoreUpdateInput
  ): Promise<StateStore | null> {
    try {
      return await this.service.updateStateStore({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          location: true,
          stateId: true,
          managerId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: StateStore })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStateStore(
    @common.Param() params: StateStoreWhereUniqueInput
  ): Promise<StateStore | null> {
    try {
      return await this.service.deleteStateStore({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          location: true,
          stateId: true,
          managerId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/warehouses")
  @ApiNestedQuery(WarehouseFindManyArgs)
  async findWarehouses(
    @common.Req() request: Request,
    @common.Param() params: StateStoreWhereUniqueInput
  ): Promise<Warehouse[]> {
    const query = plainToClass(WarehouseFindManyArgs, request.query);
    const results = await this.service.findWarehouses(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        location: true,
        capacity: true,

        stateStore: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/warehouses")
  async connectWarehouses(
    @common.Param() params: StateStoreWhereUniqueInput,
    @common.Body() body: WarehouseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      warehouses: {
        connect: body,
      },
    };
    await this.service.updateStateStore({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/warehouses")
  async updateWarehouses(
    @common.Param() params: StateStoreWhereUniqueInput,
    @common.Body() body: WarehouseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      warehouses: {
        set: body,
      },
    };
    await this.service.updateStateStore({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/warehouses")
  async disconnectWarehouses(
    @common.Param() params: StateStoreWhereUniqueInput,
    @common.Body() body: WarehouseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      warehouses: {
        disconnect: body,
      },
    };
    await this.service.updateStateStore({
      where: params,
      data,
      select: { id: true },
    });
  }
}
