/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EquipmentCollectionForm } from "./EquipmentCollectionForm";
import { EquipmentCollectionFormCountArgs } from "./EquipmentCollectionFormCountArgs";
import { EquipmentCollectionFormFindManyArgs } from "./EquipmentCollectionFormFindManyArgs";
import { EquipmentCollectionFormFindUniqueArgs } from "./EquipmentCollectionFormFindUniqueArgs";
import { DeleteEquipmentCollectionFormArgs } from "./DeleteEquipmentCollectionFormArgs";
import { EquipmentCollectionFormService } from "../equipmentCollectionForm.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => EquipmentCollectionForm)
export class EquipmentCollectionFormResolverBase {
  constructor(
    protected readonly service: EquipmentCollectionFormService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EquipmentCollectionForm",
    action: "read",
    possession: "any",
  })
  async _equipmentCollectionFormsMeta(
    @graphql.Args() args: EquipmentCollectionFormCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [EquipmentCollectionForm])
  @nestAccessControl.UseRoles({
    resource: "EquipmentCollectionForm",
    action: "read",
    possession: "any",
  })
  async equipmentCollectionForms(
    @graphql.Args() args: EquipmentCollectionFormFindManyArgs
  ): Promise<EquipmentCollectionForm[]> {
    return this.service.equipmentCollectionForms(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => EquipmentCollectionForm, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EquipmentCollectionForm",
    action: "read",
    possession: "own",
  })
  async equipmentCollectionForm(
    @graphql.Args() args: EquipmentCollectionFormFindUniqueArgs
  ): Promise<EquipmentCollectionForm | null> {
    const result = await this.service.equipmentCollectionForm(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => EquipmentCollectionForm)
  @nestAccessControl.UseRoles({
    resource: "EquipmentCollectionForm",
    action: "delete",
    possession: "any",
  })
  async deleteEquipmentCollectionForm(
    @graphql.Args() args: DeleteEquipmentCollectionFormArgs
  ): Promise<EquipmentCollectionForm | null> {
    try {
      return await this.service.deleteEquipmentCollectionForm(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
