/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductRegistrationForm } from "./ProductRegistrationForm";
import { ProductRegistrationFormCountArgs } from "./ProductRegistrationFormCountArgs";
import { ProductRegistrationFormFindManyArgs } from "./ProductRegistrationFormFindManyArgs";
import { ProductRegistrationFormFindUniqueArgs } from "./ProductRegistrationFormFindUniqueArgs";
import { DeleteProductRegistrationFormArgs } from "./DeleteProductRegistrationFormArgs";
import { ProductRegistrationFormService } from "../productRegistrationForm.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ProductRegistrationForm)
export class ProductRegistrationFormResolverBase {
  constructor(
    protected readonly service: ProductRegistrationFormService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ProductRegistrationForm",
    action: "read",
    possession: "any",
  })
  async _productRegistrationFormsMeta(
    @graphql.Args() args: ProductRegistrationFormCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ProductRegistrationForm])
  @nestAccessControl.UseRoles({
    resource: "ProductRegistrationForm",
    action: "read",
    possession: "any",
  })
  async productRegistrationForms(
    @graphql.Args() args: ProductRegistrationFormFindManyArgs
  ): Promise<ProductRegistrationForm[]> {
    return this.service.productRegistrationForms(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ProductRegistrationForm, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ProductRegistrationForm",
    action: "read",
    possession: "own",
  })
  async productRegistrationForm(
    @graphql.Args() args: ProductRegistrationFormFindUniqueArgs
  ): Promise<ProductRegistrationForm | null> {
    const result = await this.service.productRegistrationForm(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProductRegistrationForm)
  @nestAccessControl.UseRoles({
    resource: "ProductRegistrationForm",
    action: "delete",
    possession: "any",
  })
  async deleteProductRegistrationForm(
    @graphql.Args() args: DeleteProductRegistrationFormArgs
  ): Promise<ProductRegistrationForm | null> {
    try {
      return await this.service.deleteProductRegistrationForm(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
