/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProductRegistrationFormService } from "../productRegistrationForm.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProductRegistrationFormCreateInput } from "./ProductRegistrationFormCreateInput";
import { ProductRegistrationForm } from "./ProductRegistrationForm";
import { ProductRegistrationFormFindManyArgs } from "./ProductRegistrationFormFindManyArgs";
import { ProductRegistrationFormWhereUniqueInput } from "./ProductRegistrationFormWhereUniqueInput";
import { ProductRegistrationFormUpdateInput } from "./ProductRegistrationFormUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProductRegistrationFormControllerBase {
  constructor(
    protected readonly service: ProductRegistrationFormService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProductRegistrationForm })
  @nestAccessControl.UseRoles({
    resource: "ProductRegistrationForm",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProductRegistrationForm(
    @common.Body() data: ProductRegistrationFormCreateInput
  ): Promise<ProductRegistrationForm> {
    return await this.service.createProductRegistrationForm({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProductRegistrationForm] })
  @ApiNestedQuery(ProductRegistrationFormFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProductRegistrationForm",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async productRegistrationForms(
    @common.Req() request: Request
  ): Promise<ProductRegistrationForm[]> {
    const args = plainToClass(
      ProductRegistrationFormFindManyArgs,
      request.query
    );
    return this.service.productRegistrationForms({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProductRegistrationForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductRegistrationForm",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async productRegistrationForm(
    @common.Param() params: ProductRegistrationFormWhereUniqueInput
  ): Promise<ProductRegistrationForm | null> {
    const result = await this.service.productRegistrationForm({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProductRegistrationForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductRegistrationForm",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProductRegistrationForm(
    @common.Param() params: ProductRegistrationFormWhereUniqueInput,
    @common.Body() data: ProductRegistrationFormUpdateInput
  ): Promise<ProductRegistrationForm | null> {
    try {
      return await this.service.updateProductRegistrationForm({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProductRegistrationForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProductRegistrationForm",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProductRegistrationForm(
    @common.Param() params: ProductRegistrationFormWhereUniqueInput
  ): Promise<ProductRegistrationForm | null> {
    try {
      return await this.service.deleteProductRegistrationForm({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
