/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EquipmentReturnFormService } from "../equipmentReturnForm.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EquipmentReturnFormCreateInput } from "./EquipmentReturnFormCreateInput";
import { EquipmentReturnForm } from "./EquipmentReturnForm";
import { EquipmentReturnFormFindManyArgs } from "./EquipmentReturnFormFindManyArgs";
import { EquipmentReturnFormWhereUniqueInput } from "./EquipmentReturnFormWhereUniqueInput";
import { EquipmentReturnFormUpdateInput } from "./EquipmentReturnFormUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EquipmentReturnFormControllerBase {
  constructor(
    protected readonly service: EquipmentReturnFormService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EquipmentReturnForm })
  @nestAccessControl.UseRoles({
    resource: "EquipmentReturnForm",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEquipmentReturnForm(
    @common.Body() data: EquipmentReturnFormCreateInput
  ): Promise<EquipmentReturnForm> {
    return await this.service.createEquipmentReturnForm({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EquipmentReturnForm] })
  @ApiNestedQuery(EquipmentReturnFormFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EquipmentReturnForm",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async equipmentReturnForms(
    @common.Req() request: Request
  ): Promise<EquipmentReturnForm[]> {
    const args = plainToClass(EquipmentReturnFormFindManyArgs, request.query);
    return this.service.equipmentReturnForms({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EquipmentReturnForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EquipmentReturnForm",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async equipmentReturnForm(
    @common.Param() params: EquipmentReturnFormWhereUniqueInput
  ): Promise<EquipmentReturnForm | null> {
    const result = await this.service.equipmentReturnForm({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EquipmentReturnForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EquipmentReturnForm",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEquipmentReturnForm(
    @common.Param() params: EquipmentReturnFormWhereUniqueInput,
    @common.Body() data: EquipmentReturnFormUpdateInput
  ): Promise<EquipmentReturnForm | null> {
    try {
      return await this.service.updateEquipmentReturnForm({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EquipmentReturnForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EquipmentReturnForm",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEquipmentReturnForm(
    @common.Param() params: EquipmentReturnFormWhereUniqueInput
  ): Promise<EquipmentReturnForm | null> {
    try {
      return await this.service.deleteEquipmentReturnForm({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
