/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  IsDate,
  ValidateNested,
} from "class-validator";
import { EnumProductStatus } from "./EnumProductStatus";
import { Type } from "class-transformer";
import { DeliveryUpdateManyWithoutProductsInput } from "./DeliveryUpdateManyWithoutProductsInput";
import { PredictionUpdateManyWithoutProductsInput } from "./PredictionUpdateManyWithoutProductsInput";
import { CustomAlertUpdateManyWithoutProductsInput } from "./CustomAlertUpdateManyWithoutProductsInput";

@InputType()
class ProductUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumProductStatus,
  })
  @IsEnum(EnumProductStatus)
  @IsOptional()
  @Field(() => EnumProductStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  registrationDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => DeliveryUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => DeliveryUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => DeliveryUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  deliveries?: DeliveryUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => PredictionUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => PredictionUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => PredictionUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  predictions?: PredictionUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => CustomAlertUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CustomAlertUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CustomAlertUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  customAlerts?: CustomAlertUpdateManyWithoutProductsInput;
}

export { ProductUpdateInput as ProductUpdateInput };
