/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumProductStatus } from "./EnumProductStatus";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { DeliveryListRelationFilter } from "../../delivery/base/DeliveryListRelationFilter";
import { PredictionListRelationFilter } from "../../prediction/base/PredictionListRelationFilter";
import { CustomAlertListRelationFilter } from "../../customAlert/base/CustomAlertListRelationFilter";

@InputType()
class ProductWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumProductStatus,
  })
  @IsEnum(EnumProductStatus)
  @IsOptional()
  @Field(() => EnumProductStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  registrationDate?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => DeliveryListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DeliveryListRelationFilter)
  @IsOptional()
  @Field(() => DeliveryListRelationFilter, {
    nullable: true,
  })
  deliveries?: DeliveryListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PredictionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PredictionListRelationFilter)
  @IsOptional()
  @Field(() => PredictionListRelationFilter, {
    nullable: true,
  })
  predictions?: PredictionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => CustomAlertListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CustomAlertListRelationFilter)
  @IsOptional()
  @Field(() => CustomAlertListRelationFilter, {
    nullable: true,
  })
  customAlerts?: CustomAlertListRelationFilter;
}

export { ProductWhereInput as ProductWhereInput };
